### ISSUE TITLE
SGI Code?

### ISSUE THREAD

**Issue by ariscop** [n64decomp/libreultra#5]
Commit 1aca5c13ca041cef86f8dc194b727361dad9c09b (current master) appears to replace the decompilation with original source code

**Comment by CrashOveride95** [comment]
> Commit 1aca5c13ca041cef86f8dc194b727361dad9c09b (current master) appears to replace the decompilation with original source code

That is taken from the SDK. Nintendo had "publicized" specific parts of the library for developers to look at and or edit

**Comment by CCF100** [comment]
> > Commit [1aca5c1](https://github.com/n64decomp/libreultra/commit/1aca5c13ca041cef86f8dc194b727361dad9c09b) (current master) appears to replace the decompilation with original source code
> 
> That is taken from the SDK. Nintendo had "publicized" specific parts of the library for developers to look at and or edit

Are there legal issues with publishing that in this repo?

**Comment by Squall-Leonhart** [comment]
There are, this should not have been done.

The SDK is only available with these public excerpts to developer network members, which nobody here is.
